# Generated by Django 3.0.1 on 2020-01-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_code', models.CharField(blank=True, max_length=100, null=True)),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('i_code', models.CharField(blank=True, max_length=100, null=True)),
                ('i_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, max_length=100, null=True)),
                ('img_src', models.IntegerField(null=True)),
                ('price', models.ImageField(blank=True, upload_to='')),
                ('link', models.URLField(unique=True, verbose_name='url')),
                ('c_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='dkea.Category')),
            ],
        ),
    ]
